### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by piyush168713** [piyush168713/piyush168713#2]
### **Leave a comment 💬 on the issue and get featured on my README 📖!**

![129272507-69a64e18-000f-4dbf-8711-cea4f08c7ba9](https://user-images.githubusercontent.com/81097447/132379525-3bae8c1c-42e2-4be6-9d7a-47a7da067402.gif)

**Comment by SparkScratch-P** [comment]
Well.. ur Readme is fantastic! 

Where do i get such badges... the languages one? pls help

**Comment by piyush168713** [comment]
Firstly Thankyou so much @SparkScratch-P 

@SparkScratch-P  You can use my code freely and change the link path of badges or you can clone my repository and then upload it in yours.
Link of repo - https://github.com/piyush168713/piyush168713.git

use command to clone- "git clone https://github.com/piyush168713/piyush168713.git" git bash command prompt
Also check https://forthebadge.com/
and https://github.com/piyush168713/ColoredBadges.git

**Comment by piyush168713** [comment]
> Well.. ur Readme is fantastic!
> 
> Where do i get such badges... the languages one? pls help

**Comment by SparkScratch-P** [comment]
hmm.. thanks bhaiya .. this was what I needed https://github.com/piyush168713/ColoredBadges.git Starred!

**Comment by piyush168713** [comment]
> hmm.. thanks bhaiya .. this was what I needed https://github.com/piyush168713/ColoredBadges.git Starred!
> 

you're welcome.,,,@SparkScratch-P
